#!/bin/bash

samtools=$3
fn=`basename $1`
$samtools view -h $1 > $fn.tp3
cat $fn.tp3 | grep -v ^@ | cut -f10 | uniq -c | awk '{print$1,$2}' > $fn.tp
rm $fn.tp3
python make_fasta.py $fn
python count_qmer.py $fn 13
rm $fn.tp $fn.tp2
mkdir -p $2
mv $fn.qmer_* $2

