#!/bin/bash

fn=`basename $1`
cwd=`dirname "${0}"`
cat $1 | grep -v ^@ | grep NH:i:1 | cut -f10 | sort | uniq -c | awk '{print$1,$2}' > $fn.tp
python $cwd/count_qmer.py $fn.tp $3
rm $fn.tp
mkdir -p $2
mv ${fn}*.qmer_* $2
for i in `ls $2`;do
	mv $2/$i $2/`echo $i | awk -F "qmer_" '{print $2}'`
done

